/* ============================================================
   Definición de los 5 formatos reales de DistriElectronic
   (basados en los PDF guía de la carpeta /pdfs).

   Tipos de campo:
   text | textarea | date | number | select | items | images |
   signature | checklist
   - "half: true" pone dos campos en la misma fila.
   - items: colCant / colDesc personalizan encabezados; withPrice agrega precios.
   - checklist: rows [{key,label}] + options [...] (mismo select por fila).
   - signature: nameKey indica el campo de texto con el nombre del firmante.
   ============================================================ */

const CHK_ESTADO = ["Bien", "Mal", "Regular", "N/A", "NAC", "NP"];
const CHK_SINO = ["Sí", "No"];
const CHK_BRM = ["Bueno", "Regular", "Malo"];

/* Iconos SVG (trazo, estilo Feather) */
const svg = (paths) =>
  `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">${paths}</svg>`;
window.ICONS = {
  clipboard: svg('<path d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2"/><rect x="8" y="2" width="8" height="4" rx="1"/><line x1="9" y1="12" x2="15" y2="12"/><line x1="9" y1="16" x2="15" y2="16"/>'),
  battery: svg('<rect x="2" y="7" width="16" height="10" rx="2"/><line x1="22" y1="11" x2="22" y2="13"/><line x1="6" y1="10" x2="6" y2="14"/><line x1="10" y1="10" x2="10" y2="14"/>'),
  zap: svg('<polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"/>'),
  snow: svg('<line x1="12" y1="2" x2="12" y2="22"/><line x1="3.3" y1="7" x2="20.7" y2="17"/><line x1="20.7" y1="7" x2="3.3" y2="17"/>'),
  video: svg('<polygon points="23 7 16 12 23 17 23 7"/><rect x="1" y="5" width="15" height="14" rx="2"/>'),
  trash: svg('<polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/>'),
  edit: svg('<path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/>'),
  camera: svg('<path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/>'),
  folder: svg('<path d="M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2z"/>'),
};

window.FORMATS = {
  actividades: {
    name: "FORMATO DE ACTIVIDADES",
    icon: window.ICONS.clipboard,
    desc: "Actividades realizadas y material utilizado en un servicio.",
    docTitle: "FORMATO DE ACTIVIDADES",
    prefix: "ACT",
    fields: [
      { section: "Datos generales" },
      { key: "cliente", label: "Empresa", type: "text", required: true, half: true },
      { key: "ciudad", label: "Ciudad", type: "text", half: true },
      { key: "direccion", label: "Dirección", type: "text", half: true },
      { key: "fecha", label: "Fecha", type: "date", required: true, half: true },
      { key: "hora_servicio", label: "Hora de servicio", type: "text", half: true, placeholder: "Ej: 8:00 a.m. - 12:00 m." },
      { section: "Actividad realizada" },
      { key: "actividades", label: "Actividades", type: "items", colCant: "Ítem", colDesc: "Descripción" },
      { section: "Material utilizado o anotaciones" },
      { key: "materiales", label: "Materiales", type: "items", colCant: "Cantidad", colDesc: "Descripción" },
      { section: "Evidencia fotográfica" },
      { key: "imagenes", label: "Fotos del servicio", type: "images" },
      { section: "Firmas" },
      { key: "firma_funcionario", label: "Firma del funcionario", type: "signature", nameKey: "nombre_funcionario" },
      { key: "nombre_funcionario", label: "Nombre del funcionario", type: "text", half: true },
      { key: "firma_trabajador", label: "Firma del trabajador", type: "signature", nameKey: "nombre_trabajador" },
      { key: "nombre_trabajador", label: "Nombre del trabajador", type: "text", half: true },
    ],
  },

  ups: {
    name: "Formato Mantenimiento de UPS 2017",
    icon: window.ICONS.battery,
    desc: "Diagnóstico, mantenimiento o instalación de UPS con medidas eléctricas.",
    docTitle: "REPORTE TÉCNICO — UPS",
    prefix: "OTT",
    fields: [
      { section: "Tipo de servicio" },
      { key: "tipo_servicio", label: "Servicio", type: "select", required: true, half: true,
        options: ["A - Diagnóstico", "B - Mantenimiento preventivo", "C - Mantenimiento correctivo", "D - Instalación"] },
      { key: "condicion", label: "Condición", type: "select", half: true,
        options: ["Garantía", "Contrato", "Orden de trabajo"] },
      { key: "estado_equipo_inicio", label: "Estado del equipo", type: "select", half: true,
        options: ["Energizado", "Desenergizado"] },
      { section: "Datos del cliente" },
      { key: "cliente", label: "Cliente", type: "text", required: true, half: true },
      { key: "fecha", label: "Fecha", type: "date", required: true, half: true },
      { key: "direccion", label: "Dirección", type: "text", half: true },
      { key: "oficina", label: "Oficina / Sucursal", type: "text", half: true },
      { key: "lugar", label: "Lugar", type: "text", half: true },
      { key: "ciudad", label: "Ciudad", type: "text", half: true },
      { section: "Datos del equipo" },
      { key: "marca", label: "Marca", type: "text", half: true },
      { key: "modelo", label: "Modelo", type: "text", half: true },
      { key: "potencia", label: "Potencia (KVA)", type: "text", half: true },
      { key: "serie", label: "Serie", type: "text", half: true },
      { key: "inventario", label: "Inventario", type: "text", half: true },
      { key: "bancos_baterias", label: "N° de bancos de baterías", type: "text", half: true, placeholder: "Ej: 1" },
      { key: "baterias_cantidad", label: "N° de baterías", type: "text", half: true, placeholder: "Ej: 20" },
      { key: "referencia_baterias", label: "Referencia de baterías", type: "text", half: true, placeholder: "Ej: RT12100" },
      { key: "marca_baterias", label: "Marca de baterías", type: "text", half: true, placeholder: "Ej: RITAR" },
      { section: "Procedimiento" },
      { key: "procedimiento", label: "Procedimiento seguido, repuestos utilizados y alarmas o daños encontrados", type: "textarea", required: true },
      { section: "Medidas sobre el equipo" },
      { key: "voltaje_entrada", label: "Voltaje de entrada — VAB/VBC/VCA/VAN/VBN/VCN", type: "text", half: true, placeholder: "Ej: 208/208/209/120/121/120" },
      { key: "voltaje_salida", label: "Voltaje de salida — VAB/VBC/VCA/VAN/VBN/VCN", type: "text", half: true, placeholder: "Ej: 208/208/209/120/121/120" },
      { key: "voltaje_bypass", label: "Voltaje del bypass — VAB/VBC/VCA/VAN/VBN/VCN", type: "text", half: true },
      { key: "corrientes_entrada", label: "Corrientes de entrada (A/B/C)", type: "text", half: true, placeholder: "Ej: 12 / 11.8 / 12.1 Amp" },
      { key: "corrientes_salida", label: "Corrientes de salida (A/B/C)", type: "text", half: true },
      { key: "voltaje_neutro_tierra", label: "Voltaje neutro/tierra (VAC)", type: "text", half: true },
      { key: "corriente_neutro", label: "Corriente por neutro (Amp)", type: "text", half: true },
      { key: "corriente_tierra", label: "Corriente por tierra (Amp)", type: "text", half: true },
      { key: "frecuencia", label: "Frecuencia entrada/salida (Hz)", type: "text", half: true, placeholder: "Ej: 60 / 60" },
      { key: "temperatura", label: "Temperatura de la UPS (°C)", type: "text", half: true },
      { key: "voltaje_cargador", label: "Voltaje cargador de baterías (VDC)", type: "text", half: true },
      { key: "corriente_cargador", label: "Corriente cargador (A)", type: "text", half: true },
      { key: "potencia_utilizada", label: "Potencia utilizada (KW / KVA)", type: "text", half: true },
      { key: "factor_potencia", label: "Factor de potencia (PF)", type: "text", half: true },
      { key: "voltajes_medidos", label: "Voltajes medidos", type: "select", half: true,
        options: ["Aceptables", "Muy altos", "Muy bajos"] },
      { section: "Banco de baterías" },
      { key: "baterias_libres_mant", label: "Baterías libres de mantenimiento", type: "select", half: true, options: CHK_SINO },
      { key: "baterias_ubicacion", label: "Baterías", type: "select", half: true, options: ["Internas", "Externas", "Internas y externas"] },
      { key: "chk_baterias", label: "Actividades sobre baterías", type: "checklist", options: CHK_SINO, rows: [
        { key: "reposicion_electrolitico", label: "Reposición nivel electrolítico" },
        { key: "gravedad_especifica", label: "Medición gravedad específica" },
        { key: "voltaje_cada_bateria", label: "Medición voltaje en cada batería" },
      ]},
      { key: "voltajes_baterias", label: "Voltaje por batería (opcional)", type: "items", colCant: "Batería N°", colDesc: "Voltaje (VDC)" },
      { section: "Inspección visual" },
      { key: "chk_inspeccion", label: "Inspección", type: "checklist", options: CHK_ESTADO, rows: [
        { key: "luces_displays", label: "Luces indicadoras y displays" },
        { key: "extractores", label: "Extractores de aire" },
        { key: "filtros_aire", label: "Filtros de aire" },
        { key: "breakers", label: "Interruptores y/o breakers" },
        { key: "ventilacion_cuarto", label: "Ventilación del cuarto" },
        { key: "aseo_cuarto", label: "Aseo del cuarto" },
      ]},
      { key: "chk_riesgos", label: "Condiciones del sitio", type: "checklist", options: CHK_SINO, rows: [
        { key: "material_metalico", label: "Presencia de material metálico cerca de la UPS" },
        { key: "derrame_liquidos", label: "Derrame de líquidos, humedad en general" },
        { key: "papeles_cuarto", label: "Presencia de papeles en el cuarto" },
        { key: "combustible_cuarto", label: "Combustible en cuartos de UPS y/o baterías" },
        { key: "cuarto_deposito", label: "Cuartos de UPS/baterías usados como depósitos" },
      ]},
      { section: "Revisión general" },
      { key: "chk_revision", label: "Revisión", type: "checklist", options: CHK_SINO, rows: [
        { key: "limpieza_equipo", label: "Limpieza del equipo" },
        { key: "limpieza_baterias", label: "Limpieza superior de las baterías" },
        { key: "soplado_interno", label: "Soplado interno del equipo" },
        { key: "sonido_inversor", label: "Sonido (tono) normal del inversor" },
        { key: "sonido_ventiladores", label: "Sonido (tono) normal de los ventiladores" },
        { key: "revision_conectores", label: "Revisión de conectores" },
        { key: "retorqueo", label: "Retorqueo de tuercas y tornillos" },
        { key: "revision_tarjeteria", label: "Revisión de tarjetería" },
        { key: "sonidos_extranos", label: "Sonidos extraños" },
        { key: "cableado_bueno", label: "Cableado en buenas condiciones" },
      ]},
      { section: "Estado final del equipo" },
      { key: "chk_final", label: "Estado final", type: "checklist", options: CHK_SINO, rows: [
        { key: "reparado", label: "Reparado" },
        { key: "funcionando", label: "Funcionando" },
        { key: "se_puede_reparar", label: "Se puede reparar" },
        { key: "equipo_en_linea", label: "Equipo en línea" },
        { key: "fuera_servicio", label: "Equipo fuera de servicio" },
      ]},
      { key: "duracion_mantenimiento", label: "Duración aproximada del mantenimiento", type: "text", half: true },
      { key: "diagnostico", label: "Diagnóstico y observaciones generales", type: "textarea" },
      { section: "Evidencia fotográfica" },
      { key: "imagenes", label: "Fotos del servicio", type: "images" },
      { section: "Datos y firma del cliente" },
      { key: "firma_nombre", label: "Nombre (legible)", type: "text", half: true },
      { key: "firma_cargo", label: "Cargo", type: "text", half: true },
      { key: "firma_telefono", label: "Teléfono", type: "text", half: true },
      { key: "firma_email", label: "E-mail", type: "text", half: true },
      { key: "firma", label: "Firma del cliente", type: "signature", nameKey: "firma_nombre" },
      { section: "Técnico DistriElectronic" },
      { key: "tecnico", label: "Nombre del técnico", type: "text", half: true },
      { key: "firma_tecnico", label: "Firma del técnico", type: "signature", nameKey: "tecnico" },
    ],
  },

  plantas: {
    name: "FORMATO MANTENIMIENTO PLANTAS ELCTRICAS",
    icon: window.ICONS.zap,
    desc: "Reporte de mantenimiento preventivo de plantas eléctricas.",
    docTitle: "REPORTE DE MANTENIMIENTO PREVENTIVO DE PLANTAS ELÉCTRICAS",
    prefix: "PLE",
    fields: [
      { section: "Datos generales" },
      { key: "cliente", label: "Cliente", type: "text", required: true, half: true },
      { key: "fecha", label: "Fecha", type: "date", required: true, half: true },
      { key: "direccion", label: "Dirección", type: "text", half: true },
      { key: "oficina", label: "Oficina / Cod. oficina", type: "text", half: true },
      { key: "lugar", label: "Lugar", type: "text", half: true },
      { key: "ciudad", label: "Ciudad", type: "text", half: true },
      { key: "condicion", label: "Condición", type: "select", half: true,
        options: ["Garantía", "Contrato", "Orden de trabajo", "Solicitud escrita o telefónica"] },
      { key: "estado_equipo_inicio", label: "Estado del equipo", type: "select", half: true,
        options: ["Energizado", "Desenergizado"] },
      { section: "Motor y generador" },
      { key: "motor_marca", label: "Motor — Marca", type: "text", half: true },
      { key: "motor_modelo", label: "Motor — Modelo", type: "text", half: true },
      { key: "motor_potencia", label: "Motor — Potencia", type: "text", half: true },
      { key: "combustible", label: "Combustible", type: "select", half: true, options: ["Diesel", "Gasolina", "Gas"] },
      { key: "gen_marca", label: "Generador — Marca", type: "text", half: true },
      { key: "gen_modelo", label: "Generador — Modelo", type: "text", half: true },
      { key: "gen_potencia", label: "Generador — Potencia", type: "text", half: true },
      { key: "serie", label: "No. de serie", type: "text", half: true },
      { key: "inventario", label: "Inventario", type: "text", half: true },
      { key: "baterias_ref", label: "Batería(s) — Referencia(s)", type: "text", half: true },
      { section: "Revisión eléctrica del generador" },
      { key: "voltaje_salida", label: "Voltaje de salida (VAB/VBC/VCA · VAN/VBN/VCN)", type: "text", half: true },
      { key: "corrientes_salida", label: "Corrientes de salida (IA/IB/IC)", type: "text", half: true },
      { key: "frecuencia", label: "Frecuencia en vacío / con carga (Hz)", type: "text", half: true },
      { key: "breaker", label: "Breaker — corriente y estado", type: "text", half: true, placeholder: "Ej: 100 A, bueno" },
      { key: "precalentador", label: "Precalentador funcionando", type: "select", half: true, options: CHK_SINO },
      { key: "voltaje_baterias", label: "Baterías — Voltaje total (VDC)", type: "text", half: true },
      { key: "cargador_externo", label: "Cargador externo de baterías", type: "select", half: true, options: ["Bueno", "Malo", "No tiene"] },
      { key: "medidores", label: "Medidores (voltaje / corriente)", type: "select", half: true, options: ["Buenos", "Malos", "No tiene"] },
      { key: "chk_baterias", label: "Baterías", type: "checklist", options: CHK_SINO, rows: [
        { key: "libres_mantenimiento", label: "Libres de mantenimiento" },
        { key: "reposicion_electrolitico", label: "Reposición nivel electrolítico" },
        { key: "gravedad_especifica", label: "Medición gravedad específica" },
        { key: "voltaje_cada_bateria", label: "Medición voltaje en cada batería" },
        { key: "bornes_buenos", label: "Bornes buenos" },
        { key: "bornes_sulfatados", label: "Bornes sulfatados" },
      ]},
      { section: "Revisión mecánica del motor" },
      { key: "chk_motor", label: "Revisión mecánica", type: "checklist", options: CHK_ESTADO, rows: [
        { key: "presion_aceite", label: "Presión de aceite" },
        { key: "filtro_aceite", label: "Filtro de aceite" },
        { key: "temperatura", label: "Temperatura" },
        { key: "nivel_lubricante", label: "Nivel de lubricante" },
        { key: "tension_correas", label: "Tensión de las correas" },
        { key: "nivel_combustible", label: "Nivel de combustible" },
        { key: "nivel_refrigerante", label: "Nivel del refrigerante" },
        { key: "drenaje_prefiltros", label: "Drenaje sólidos y agua en prefiltros" },
        { key: "motor_arranque", label: "Estado del motor de arranque" },
        { key: "alternador", label: "Estado de servicio del alternador" },
      ]},
      { key: "chk_fugas", label: "Fugas", type: "checklist", options: CHK_SINO, rows: [
        { key: "fugas_aceite", label: "Fugas de aceite" },
        { key: "fugas_combustible", label: "Fugas de combustible" },
      ]},
      { section: "Revisión general del sistema" },
      { key: "chk_sistema", label: "Estado general", type: "checklist", options: CHK_ESTADO, rows: [
        { key: "luces_displays", label: "Luces indicadoras y displays" },
        { key: "extractores", label: "Extractores de aire" },
        { key: "filtros_aire", label: "Filtros de aire" },
        { key: "breakers", label: "Interruptores y/o breakers" },
        { key: "ventilacion", label: "Ventilación del lugar" },
        { key: "aseo", label: "Aseo del lugar" },
        { key: "protecciones", label: "Protecciones eléctricas" },
        { key: "cableado_senal", label: "Cableado de señalización" },
        { key: "cableado_potencia", label: "Cableado de potencia" },
      ]},
      { key: "chk_sitio", label: "Condiciones del sitio", type: "checklist", options: CHK_SINO, rows: [
        { key: "material_metalico", label: "Material metálico cerca de la planta" },
        { key: "liquidos_derramados", label: "Líquidos derramados / humedad general" },
        { key: "papeles_sitio", label: "Presencia de papeles en el sitio" },
        { key: "combustible_ok", label: "Combustible almacenado adecuadamente" },
        { key: "sitio_deposito", label: "Sitio del equipo utilizado como depósito" },
      ]},
      { key: "chk_limpieza", label: "Limpieza y revisión", type: "checklist", options: CHK_SINO, rows: [
        { key: "limpieza_equipo", label: "Limpieza del equipo" },
        { key: "limpieza_baterias", label: "Limpieza de las baterías" },
        { key: "sonido_ventiladores", label: "Sonido normal de los ventiladores" },
        { key: "sonido_motor", label: "Sonido normal del motor" },
        { key: "sonido_arranque", label: "Sonido normal del motor de arranque" },
        { key: "revision_conectores", label: "Revisión de conectores" },
        { key: "retorqueo", label: "Retorqueo de tuercas y tornillos" },
        { key: "revision_tarjeteria", label: "Revisión de tarjetería" },
      ]},
      { section: "Revisión del tablero y pruebas" },
      { key: "chk_tablero", label: "Tablero", type: "checklist", options: CHK_SINO, rows: [
        { key: "totalizador", label: "Totalizador de salida a carga" },
        { key: "breaker_distribucion", label: "Breaker de distribución" },
      ]},
      { key: "chk_pruebas", label: "Pruebas", type: "checklist", options: ["Sí - Bien", "Sí - Mal", "No"], rows: [
        { key: "arranque_planta", label: "Arranque de la planta" },
        { key: "transferencia_automatica", label: "Transferencia automática" },
        { key: "transferencia_manual", label: "Transferencia manual" },
      ]},
      { key: "horometro", label: "Registro del horómetro", type: "text", half: true },
      { key: "funcionamiento_previo", label: "Funcionamiento en días anteriores", type: "select", half: true,
        options: ["Correcto", "Incorrecto", "No saben"] },
      { section: "Trabajo realizado" },
      { key: "trabajo_realizado", label: "Trabajo realizado", type: "textarea", required: true },
      { key: "observaciones", label: "Observaciones y comentarios acerca del sistema", type: "textarea" },
      { section: "Evidencia fotográfica" },
      { key: "imagenes", label: "Fotos del servicio", type: "images" },
      { section: "Datos y firma del cliente" },
      { key: "firma_nombre", label: "Nombre (legible)", type: "text", half: true },
      { key: "firma_cargo", label: "Cargo", type: "text", half: true },
      { key: "firma_telefono", label: "Teléfono", type: "text", half: true },
      { key: "firma_email", label: "E-mail", type: "text", half: true },
      { key: "firma", label: "Firma del cliente", type: "signature", nameKey: "firma_nombre" },
      { section: "Técnico DistriElectronic" },
      { key: "tecnico", label: "Nombre del técnico", type: "text", half: true },
      { key: "firma_tecnico", label: "Firma del técnico", type: "signature", nameKey: "tecnico" },
    ],
  },

  aire: {
    name: "REPORTE TECNICO - A.A - DISTRI",
    icon: window.ICONS.snow,
    desc: "Informe técnico de mantenimiento de equipos de aire acondicionado.",
    docTitle: "MANTENIMIENTO EQUIPOS DE AIRE ACONDICIONADO",
    prefix: "AA",
    fields: [
      { section: "Datos generales" },
      { key: "cliente", label: "Empresa", type: "text", required: true, half: true },
      { key: "fecha", label: "Fecha", type: "date", required: true, half: true },
      { key: "ciudad", label: "Ciudad", type: "text", half: true },
      { key: "sucursal", label: "Sucursal", type: "text", half: true },
      { key: "direccion", label: "Dirección", type: "text", half: true },
      { key: "telefono", label: "Teléfono", type: "text", half: true },
      { key: "contacto", label: "Contacto", type: "text", half: true },
      { key: "area", label: "Área", type: "text", half: true },
      { section: "Descripción del equipo" },
      { key: "marca", label: "Marca", type: "text", half: true },
      { key: "capacidad", label: "Capacidad (BTU/H)", type: "text", half: true },
      { key: "tipo_equipo", label: "Tipo de equipo", type: "select", half: true,
        options: ["Mini Split", "Piso Techo", "Cassete", "Paquete", "Ventana", "Split Central", "Portátil", "Precisión"] },
      { key: "trabajo", label: "Trabajo a realizar", type: "select", required: true, half: true,
        options: ["Mantenimiento preventivo", "Mantenimiento correctivo", "Instalación", "Garantía"] },
      { key: "tipo_servicio", label: "Tipo", type: "select", half: true, options: ["Visita", "Laboratorio"] },
      { key: "ubicacion_manejadora", label: "Ubicación manejadora", type: "text", half: true },
      { key: "ubicacion_condensadora", label: "Ubicación condensadora", type: "text", half: true },
      { key: "manejadora_modelo", label: "Unidad manejadora — Modelo", type: "text", half: true },
      { key: "manejadora_serie", label: "Unidad manejadora — Serie", type: "text", half: true },
      { key: "condensadora_modelo", label: "Unidad condensadora — Modelo", type: "text", half: true },
      { key: "condensadora_serie", label: "Unidad condensadora — Serie", type: "text", half: true },
      { section: "Tiempos de ejecución del servicio" },
      { key: "hora_inicio", label: "Hora y fecha inicio servicio", type: "text", half: true, placeholder: "Ej: 8:00 a.m. — 15/07/2026" },
      { key: "hora_fin", label: "Hora y fecha fin servicio", type: "text", half: true },
      { section: "Lista de verificación" },
      { key: "chk_verificacion", label: "Verificación (Bueno / Regular / Malo)", type: "checklist", options: CHK_BRM, rows: [
        { key: "funcionamiento", label: "Funcionamiento" },
        { key: "carga_refrigerante", label: "Carga refrigerante" },
        { key: "serpentin_condensador", label: "Serpentín condensador" },
        { key: "serpentin_manejadora", label: "Serpentín manejadora" },
        { key: "filtros_aire", label: "Filtros aire" },
        { key: "ventilador_condensador", label: "Ventilador condensador" },
        { key: "ventilador_manejadora", label: "Ventilador manejadora" },
        { key: "bomba_condensado", label: "Bomba de condensado" },
        { key: "revision_escapes", label: "Tubería de refrig. — Revisión de escapes" },
        { key: "aislamiento", label: "Tubería de refrig. — Aislamiento" },
        { key: "soportes", label: "Tubería de refrig. — Soportes" },
        { key: "breakers", label: "Tablero eléctrico — Breakers" },
        { key: "contactores", label: "Tablero eléctrico — Contactores" },
        { key: "cableado", label: "Tablero eléctrico — Cableado" },
      ]},
      { section: "Informe técnico" },
      { key: "informe", label: "Informe técnico", type: "textarea", required: true },
      { key: "observaciones", label: "Observaciones generales", type: "textarea" },
      { key: "pendientes", label: "Pendientes", type: "textarea" },
      { section: "Evidencia fotográfica" },
      { key: "imagenes", label: "Fotos del servicio", type: "images" },
      { section: "Firma del técnico" },
      { key: "tecnico", label: "Nombre del técnico", type: "text", half: true },
      { key: "cc_tecnico", label: "C.C. del técnico", type: "text", half: true },
      { key: "firma_tecnico", label: "Firma del técnico", type: "signature", nameKey: "tecnico" },
      { section: "Firma del cliente" },
      { key: "firma_nombre", label: "Nombre del cliente", type: "text", half: true },
      { key: "cc_cliente", label: "C.C. del cliente", type: "text", half: true },
      { key: "firma", label: "Firma del cliente", type: "signature", nameKey: "firma_nombre" },
    ],
  },

  cctv: {
    name: "REPORTE TECNICO CCTV",
    icon: window.ICONS.video,
    desc: "Revisión y mantenimiento de cámaras y sistemas CCTV.",
    docTitle: "REPORTE TÉCNICO CCTV",
    prefix: "CCTV",
    fields: [
      { section: "Datos principales" },
      { key: "cliente", label: "Cliente", type: "text", required: true, half: true },
      { key: "fecha", label: "Fecha", type: "date", required: true, half: true },
      { key: "direccion", label: "Dirección", type: "text", half: true },
      { key: "ciudad", label: "Ciudad", type: "text", half: true },
      { key: "lugar", label: "Lugar", type: "text", half: true },
      { key: "equipo", label: "Equipo", type: "text", half: true },
      { key: "marca", label: "Marca", type: "text", half: true },
      { key: "modelo", label: "Modelo", type: "text", half: true },
      { key: "serie", label: "Serie", type: "text", half: true },
      { key: "tecnologia", label: "Tecnología de cámara", type: "select", half: true, options: ["IP", "Análoga"] },
      { key: "tipo_camara", label: "Tipo de cámara", type: "select", half: true,
        options: ["Domo PTZ", "Fija bala", "Fija mini domo", "Fija con housing", "Fija 360°"] },
      { section: "Lista de chequeo de componentes" },
      { key: "chk_componentes", label: "Estado de componentes", type: "checklist", options: CHK_ESTADO, rows: [
        { key: "estado_fisico", label: "Estado físico de cámara" },
        { key: "acrilico", label: "Estado de acrílico protector" },
        { key: "fuente_dc", label: "Estado de fuente DC" },
        { key: "balums", label: "Estado de balums" },
        { key: "cableado", label: "Estado de cableado" },
        { key: "voltaje_alimentacion", label: "Voltaje de alimentación" },
        { key: "dvr_nvr", label: "Estado de DVR/NVR" },
      ]},
      { key: "chk_tareas", label: "Tareas", type: "checklist", options: CHK_SINO, rows: [
        { key: "ajuste_conectores", label: "Ajuste de conectores" },
        { key: "limpieza_equipo", label: "Limpieza del equipo" },
        { key: "limpieza_lente", label: "Limpieza de lente y acrílico" },
        { key: "camara_operativa", label: "Cámara operativa" },
      ]},
      { key: "detalles", label: "Detalles", type: "textarea" },
      { section: "Diagnóstico" },
      { key: "diagnostico", label: "Tarea realizada, diagnóstico y observaciones generales", type: "textarea", required: true },
      { section: "Evidencia fotográfica" },
      { key: "imagenes", label: "Fotos del servicio", type: "images" },
      { section: "Datos y firma del cliente" },
      { key: "firma_nombre", label: "Nombre (legible)", type: "text", half: true },
      { key: "firma_cargo", label: "Cargo", type: "text", half: true },
      { key: "firma_telefono", label: "Teléfono", type: "text", half: true },
      { key: "firma_email", label: "E-mail", type: "text", half: true },
      { key: "firma", label: "Firma del cliente", type: "signature", nameKey: "firma_nombre" },
      { section: "Técnico DistriElectronic" },
      { key: "tecnico", label: "Nombre del técnico", type: "text", half: true },
      { key: "firma_tecnico", label: "Firma del técnico", type: "signature", nameKey: "tecnico" },
    ],
  },
};
